# Generated by Django 5.2.6 on 2025-09-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
    ]
