# Generated by Django 5.2.6 on 2025-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20250914_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sentiment_label',
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Sentiment score from -1 (negative) to 1 (positive)', null=True),
        ),
    ]
