# Generated by Django 5.2.6 on 2025-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_sentiment_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='app_id',
            field=models.CharField(blank=True, help_text='The app store ID this review belongs to', max_length=255, null=True),
        ),
    ]
