# Generated by Django 5.2.6 on 2025-09-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_project_competitorapp_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_analysis_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
