# Generated by Django 5.2.6 on 2025-09-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_userprofile_last_analysis_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='analyses_this_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_analysis_reset',
        ),
        migrations.AddField(
            model_name='competitorapp',
            name='last_refreshed',
            field=models.DateTimeField(blank=True, help_text='When reviews were last fetched for this competitor app', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='home_app_last_refreshed',
            field=models.DateTimeField(blank=True, help_text='When reviews were last fetched for the home app', null=True),
        ),
    ]
