# Generated by Django 5.2.6 on 2025-09-17 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_userprofile_analyses_this_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('quick', 'Quick Analysis'), ('full', 'Full Analysis'), ('refresh', 'Data Refresh')], max_length=20)),
                ('app_id', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('progress', 'In Progress'), ('success', 'Completed'), ('failure', 'Failed'), ('revoked', 'Cancelled')], default='pending', max_length=20)),
                ('current_reviews', models.IntegerField(default=0)),
                ('target_reviews', models.IntegerField(default=200)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
