# Generated by Django 5.2.6 on 2025-09-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_tasktracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('positive_percentage', models.FloatField()),
                ('negative_percentage', models.FloatField()),
                ('neutral_percentage', models.FloatField()),
                ('total_reviews_analyzed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('app_id', 'date')},
            },
        ),
    ]
