# Generated by Django 5.2.6 on 2025-09-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_create_competitorapp'),
    ]

    operations = [
    ]
