# Generated by Django 5.2.6 on 2025-10-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorapp',
            name='apple_app_id',
            field=models.CharField(blank=True, help_text='Apple App Store numeric ID (e.g., 389801252)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='apple_app_id',
            field=models.CharField(blank=True, help_text='Apple App Store numeric ID (e.g., 389801252)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='counts_toward_score',
            field=models.BooleanField(default=True, help_text='Whether this review counts toward sentiment metrics (True for app stores, False for social mentions)'),
        ),
    ]
